### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by krymancer** [Krymancer/cardapio-bot#1]
- [x] Colocar os botões de ações do bot na conversa
- [x] Corrigir problema de fim de semana
- [ ] Deixar os "!" (aviso de contém glúten/lactose) apenas quando necessário
- [ ] Novas features: como por exemplo notificação automatizada.
